type: atm
setup:
  displacement: 38.0 A

  solvent:
    ionic_strength: 0.0 M
    neutralize: true
    cation: K+
    anion: Cl-

    water_model: tip3p
    tleap_sources:
    - leaprc.water.tip3p

    box_padding: 8.5 A
    n_waters: null

  restraints:
    com:
      type:   flat-bottom
      k:      25.0 kcal * mol**-1 * A**-2
      radius: 5.0 A
    alignment:
      type: atm
      k_distance: 2.5  kcal * mol**-1 * A**-2
      k_angle:    10.0 kcal * mol**-1
      k_dihedral: 10.0 kcal * mol**-1
    receptor:
      type:   flat-bottom
      k:      25.0 kcal * mol**-1 * A**-2
      radius: 0.5 A
    receptor_query: '@1-40'

  apply_hmr: false
  apply_rest: false

states:
  lambda_1:  [ 0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00 ]
  lambda_2:  [ 0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00 ]
  direction: [ 1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1 ]
  alpha:     [ 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00 ]
  u0:        [ 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00 ]
  w0:        [ 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00 ]

equilibrate:
  stages:
  - type: minimization
    restraints:
      '!(:WAT,CL,NA,K) & !@/H':
        type: flat-bottom
        k: 25.0 kcal * mol**-1 * A**-2
        radius: 1.5 A
    tolerance: 10.0 kcal * mol**-1 * A**-1
    max_iterations: 0

  - type: anneal

    integrator:
      type: langevin
      timestep: 0.001 ps
      friction: 1.0 ps**-1
      constraint_tolerance: 1.0e-06

    restraints:
      '!(:WAT,CL,NA,K) & !@/H':
        type: flat-bottom
        k: 25.0 kcal * mol**-1 * A**-2
        radius: 1.5 A

    temperature_initial: 50.0 K
    temperature_final: 300.0 K

    n_steps: 25000
    frequency: 5000

  - type: simulation

    integrator:
      type: langevin
      timestep: 0.001 ps
      friction: 1.0 ps**-1

    restraints:
      '!(:WAT,CL,NA,K) & !@/H':
        type:   flat-bottom
        k:      25.0 kcal * mol**-1 * A**-2
        radius: 1.5 A

    temperature: 300.0 K

    pressure: 1.0 bar
    barostat_frequency: 25

    n_steps: 25000

  report_interval: 5000

  soft_core:
    u_max: 1000 kcal * mol**-1
    u0:    500  kcal * mol**-1
    a:     0.0625

sample:
  integrator:
    type: langevin
    timestep: 0.002 ps
    friction: 1.0 ps**-1

  temperature: 300.0 K

  n_warmup_steps: 25000

  n_steps_per_cycle: 500
  n_cycles: 1000

  max_step_retries: 5
  swap_mode: all

  max_swaps: null

  trajectory_interval: 10
  analysis_interval: 10

  soft_core:
    u_max: 100 kcal * mol**-1
    u0:    50  kcal * mol**-1
    a:     0.0625
